---
title: "iteration and list columns"
output: github_document
---

```{r library loading}
library(tidyverse)
library(rvest)
```

## Iteration

### Here's some list
```{r}
l = list(
  vec_numeric = 1:4,
  unif_sample = runif(100),
  mat = matrix(1:8, nrow =2 , ncol =4, byrow = TRUE),
  summary = summary(rnorm(1000))
)

l[['mat']]

l[[4]]

```
Make a list that's hopefully a bit more useful.

```{r}
list_norms = 
  list(
    a = rnorm(20, 0, 5),
    b = rnorm(20, 4, 5),
    c = rnorm(20, 0, 10),
    d = rnorm(20, 4, 10)
  )

list_norms[['b']]
```
Let's reuse the funtion we wrote last time.

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  out_df = 
    tibble(
      mean = mean_x, 
      sd = sd_x
    )
  return (out_df)
}
```

Let's use the function to take mean and sd of all samples.

```{r}
mean_and_sd(list_norms[["a"]])
mean_and_sd(list_norms[["b"]])
mean_and_sd(list_norms[["c"]])
mean_and_sd(list_norms[["d"]])
```













